[versions]
spigot = "1.19.4-R0.1-SNAPSHOT"

placeholder = "2.11.1"

[libraries]
spigot = { group = "dev.folia", name = "folia-api", version.ref = "spigot" }

placeholder = { group = "me.clip", name = "placeholderapi", version.ref = "placeholder" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2"}